FROM golang:1.18.2

# # llのエイリアスを指定
# RUN echo "alias ll='ls -l'" >> /home/${username}/.bashrc
# RUN touch /home/${username}/.bash_profile
# RUN echo 'source ~/.bashrc' >> /home/${username}/.bash_profile

# # pingのインストール
# RUN apt-get update
# RUN apt-get install -y iputils-ping