version: '3.9'
services:
  golang:
    container_name: gin-tutorial
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/workspaces